matrix:
  include:
    - DOCKER_RUBY_VERSION: 1.9.3
      RUBY_IMAGE_TAG: 1.9.3-2

    - DOCKER_RUBY_VERSION: 2.2
      RUBY_IMAGE_TAG: 2.2-2

build:
  image: abakpress/dind:2
  privileged: true
  volumes:
    - /home/data/drone/images:/images
    - /home/data/drone/gems:/bundle
  environment:
    - COMPOSE_FILE_EXT=drone
  commands:
    - wrapdocker docker -v

    - if [ ! -e /images/ruby_$RUBY_IMAGE_TAG.tar ]; then docker pull abakpress/ruby:$RUBY_IMAGE_TAG; docker save abakpress/ruby:$RUBY_IMAGE_TAG > /images/ruby_$RUBY_IMAGE_TAG.tar; fi

    - docker load -i /images/ssh-agent.tar
    - docker load -i /images/ruby_$RUBY_IMAGE_TAG.tar

    - dip provision
    - dip rspec
